# Generated by Django 3.2.7 on 2021-09-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('available', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='yes', max_length=5, verbose_name='Available ?')),
            ],
        ),
    ]
