# Generated by Django 3.2.7 on 2021-10-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_orderitems_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rate'),
        ),
    ]
